<?php


 function autoload_982e3ab57777f1013a699229cb9c6f90($class)
{
    $classes = array(
        'DHLClient\Model\DHL24WebapiService' => __DIR__ .'/DHL24WebapiService.php',
        'DHLClient\Model\getVersion' => __DIR__ .'/getVersion.php',
        'DHLClient\Model\getVersionResponse' => __DIR__ .'/getVersionResponse.php',
        'DHLClient\Model\AuthData' => __DIR__ .'/AuthData.php',
        'DHLClient\Model\AddressData' => __DIR__ .'/AddressData.php',
        'DHLClient\Model\ReceiverAddressData' => __DIR__ .'/ReceiverAddressData.php',
        'DHLClient\Model\NeighbourAddress' => __DIR__ .'/NeighbourAddress.php',
        'DHLClient\Model\PieceDefinition' => __DIR__ .'/PieceDefinition.php',
        'DHLClient\Model\ArrayOfPiecedefinition' => __DIR__ .'/ArrayOfPiecedefinition.php',
        'DHLClient\Model\PaymentData' => __DIR__ .'/PaymentData.php',
        'DHLClient\Model\ServiceDefinition' => __DIR__ .'/ServiceDefinition.php',
        'DHLClient\Model\ShipmentFullData' => __DIR__ .'/ShipmentFullData.php',
        'DHLClient\Model\ArrayOfShipmentfulldata' => __DIR__ .'/ArrayOfShipmentfulldata.php',
        'DHLClient\Model\createShipments' => __DIR__ .'/createShipments.php',
        'DHLClient\Model\ShipmentBasicData' => __DIR__ .'/ShipmentBasicData.php',
        'DHLClient\Model\ArrayOfShipmentbasicdata' => __DIR__ .'/ArrayOfShipmentbasicdata.php',
        'DHLClient\Model\createShipmentsResponse' => __DIR__ .'/createShipmentsResponse.php',
        'DHLClient\Model\ReturnItemToPrint' => __DIR__ .'/ReturnItemToPrint.php',
        'DHLClient\Model\ArrayOfReturnitemtoprint' => __DIR__ .'/ArrayOfReturnitemtoprint.php',
        'DHLClient\Model\getReturnByWaybill' => __DIR__ .'/getReturnByWaybill.php',
        'DHLClient\Model\Label' => __DIR__ .'/Label.php',
        'DHLClient\Model\Response\CreateShipmentResponse' => __DIR__ .'/Response/CreateShipmentResponse.php',
        'DHLClient\Model\ArrayOfCreateshipmentresponse' => __DIR__ .'/ArrayOfCreateshipmentresponse.php',
        'DHLClient\Model\getReturnByWaybillResponse' => __DIR__ .'/getReturnByWaybillResponse.php',
        'DHLClient\Model\Billing' => __DIR__ .'/Billing.php',
        'DHLClient\Model\ReturnService' => __DIR__ .'/ReturnService.php',
        'DHLClient\Model\ArrayOfReturnservice' => __DIR__ .'/ArrayOfReturnservice.php',
        'DHLClient\Model\ReturnShipmentTime' => __DIR__ .'/ReturnShipmentTime.php',
        'DHLClient\Model\ReturnShipmentInfo' => __DIR__ .'/ReturnShipmentInfo.php',
        'DHLClient\Model\PreavisoContact' => __DIR__ .'/PreavisoContact.php',
        'DHLClient\Model\ShipperAddress' => __DIR__ .'/ShipperAddress.php',
        'DHLClient\Model\ReturnAddressat' => __DIR__ .'/ReturnAddressat.php',
        'DHLClient\Model\ReturnShip' => __DIR__ .'/ReturnShip.php',
        'DHLClient\Model\ReturnPackage' => __DIR__ .'/ReturnPackage.php',
        'DHLClient\Model\ArrayOfReturnpackage' => __DIR__ .'/ArrayOfReturnpackage.php',
        'DHLClient\Model\CreateReturnShipmentRequest' => __DIR__ .'/CreateReturnShipmentRequest.php',
        'DHLClient\Model\createShipmentReturn' => __DIR__ .'/createShipmentReturn.php',
        'DHLClient\Model\CreateReturnShipmentResponse' => __DIR__ .'/CreateReturnShipmentResponse.php',
        'DHLClient\Model\ArrayOfCreatereturnshipmentresponse' => __DIR__ .'/ArrayOfCreatereturnshipmentresponse.php',
        'DHLClient\Model\createShipmentReturnResponse' => __DIR__ .'/createShipmentReturnResponse.php',
        'DHLClient\Model\ArrayOfString' => __DIR__ .'/ArrayOfString.php',
        'DHLClient\Model\deleteShipments' => __DIR__ .'/deleteShipments.php',
        'DHLClient\Model\DeleteNotification' => __DIR__ .'/DeleteNotification.php',
        'DHLClient\Model\ArrayOfDeletenotification' => __DIR__ .'/ArrayOfDeletenotification.php',
        'DHLClient\Model\deleteShipmentsResponse' => __DIR__ .'/deleteShipmentsResponse.php',
        'DHLClient\Model\getMyShipments' => __DIR__ .'/getMyShipments.php',
        'DHLClient\Model\getMyShipmentsResponse' => __DIR__ .'/getMyShipmentsResponse.php',
        'DHLClient\Model\getMyShipmentsCount' => __DIR__ .'/getMyShipmentsCount.php',
        'DHLClient\Model\getMyShipmentsCountResponse' => __DIR__ .'/getMyShipmentsCountResponse.php',
        'DHLClient\Model\getPostalCodeServices' => __DIR__ .'/getPostalCodeServices.php',
        'DHLClient\Model\PostalCodeServicesResponse' => __DIR__ .'/PostalCodeServicesResponse.php',
        'DHLClient\Model\getPostalCodeServicesResponse' => __DIR__ .'/getPostalCodeServicesResponse.php',
        'DHLClient\Model\getTrackAndTraceInfo' => __DIR__ .'/getTrackAndTraceInfo.php',
        'DHLClient\Model\TrackAndTraceEvent' => __DIR__ .'/TrackAndTraceEvent.php',
        'DHLClient\Model\ArrayOfTrackandtraceevent' => __DIR__ .'/ArrayOfTrackandtraceevent.php',
        'DHLClient\Model\TrackAndTraceResponse' => __DIR__ .'/TrackAndTraceResponse.php',
        'DHLClient\Model\getTrackAndTraceInfoResponse' => __DIR__ .'/getTrackAndTraceInfoResponse.php',
        'DHLClient\Model\ShipmentOrderInfo' => __DIR__ .'/ShipmentOrderInfo.php',
        'DHLClient\Model\bookCourier' => __DIR__ .'/bookCourier.php',
        'DHLClient\Model\bookCourierResponse' => __DIR__ .'/bookCourierResponse.php',
        'DHLClient\Model\cancelCourierBooking' => __DIR__ .'/cancelCourierBooking.php',
        'DHLClient\Model\cancelCourierBookingResponse' => __DIR__ .'/cancelCourierBookingResponse.php',
        'DHLClient\Model\ItemToPrint' => __DIR__ .'/ItemToPrint.php',
        'DHLClient\Model\ArrayOfItemtoprint' => __DIR__ .'/ArrayOfItemtoprint.php',
        'DHLClient\Model\getLabels' => __DIR__ .'/getLabels.php',
        'DHLClient\Model\ItemToPrintResponse' => __DIR__ .'/ItemToPrintResponse.php',
        'DHLClient\Model\ArrayOfItemtoprintresponse' => __DIR__ .'/ArrayOfItemtoprintresponse.php',
        'DHLClient\Model\getLabelsResponse' => __DIR__ .'/getLabelsResponse.php',
        'DHLClient\Model\PnpRequest' => __DIR__ .'/PnpRequest.php',
        'DHLClient\Model\getPnp' => __DIR__ .'/getPnp.php',
        'DHLClient\Model\PnpResponse' => __DIR__ .'/PnpResponse.php',
        'DHLClient\Model\getPnpResponse' => __DIR__ .'/getPnpResponse.php',
        'DHLClient\Model\getShipmentScan' => __DIR__ .'/getShipmentScan.php',
        'DHLClient\Model\ScanToPrintResponse' => __DIR__ .'/ScanToPrintResponse.php',
        'DHLClient\Model\getShipmentScanResponse' => __DIR__ .'/getShipmentScanResponse.php',
        'DHLClient\Model\Service' => __DIR__ .'/Service.php',
        'DHLClient\Model\ArrayOfService' => __DIR__ .'/ArrayOfService.php',
        'DHLClient\Model\ShipmentTime' => __DIR__ .'/ShipmentTime.php',
        'DHLClient\Model\ShipmentInfo' => __DIR__ .'/ShipmentInfo.php',
        'DHLClient\Model\Address' => __DIR__ .'/Address.php',
        'DHLClient\Model\Addressat' => __DIR__ .'/Addressat.php',
        'DHLClient\Model\ReceiverAddress' => __DIR__ .'/ReceiverAddress.php',
        'DHLClient\Model\ReceiverAddressat' => __DIR__ .'/ReceiverAddressat.php',
        'DHLClient\Model\Ship' => __DIR__ .'/Ship.php',
        'DHLClient\Model\Package' => __DIR__ .'/Package.php',
        'DHLClient\Model\ArrayOfPackage' => __DIR__ .'/ArrayOfPackage.php',
        'DHLClient\Model\CreateShipmentRequest' => __DIR__ .'/CreateShipmentRequest.php',
        'DHLClient\Model\createShipment' => __DIR__ .'/createShipment.php',
        'DHLClient\Model\createShipmentResponse' => __DIR__ .'/createShipmentResponse.php',
        'DHLClient\Model\DeleteShipmentRequest' => __DIR__ .'/DeleteShipmentRequest.php',
        'DHLClient\Model\deleteShipment' => __DIR__ .'/deleteShipment.php',
        'DHLClient\Model\Response\DeleteShipmentResponse' => __DIR__ .'/Response/DeleteShipmentResponse.php',
        'DHLClient\Model\deleteShipmentResponse' => __DIR__ .'/deleteShipmentResponse.php',
        'DHLClient\Model\GetNearestServicepointsRequest' => __DIR__ .'/GetNearestServicepointsRequest.php',
        'DHLClient\Model\getNearestServicepoints' => __DIR__ .'/getNearestServicepoints.php',
        'DHLClient\Model\SearchAddress' => __DIR__ .'/SearchAddress.php',
        'DHLClient\Model\Point' => __DIR__ .'/Point.php',
        'DHLClient\Model\ArrayOfPoint' => __DIR__ .'/ArrayOfPoint.php',
        'DHLClient\Model\GetNearestServicepointsResponse' => __DIR__ .'/GetNearestServicepointsResponse.php',
        'DHLClient\Model\getNearestServicepointsResponse' => __DIR__ .'/getNearestServicepointsResponse.php',
        'DHLClient\Model\getInternationalParams' => __DIR__ .'/getInternationalParams.php',
        'DHLClient\Model\InternationalParam' => __DIR__ .'/InternationalParam.php',
        'DHLClient\Model\ArrayOfInternationalparam' => __DIR__ .'/ArrayOfInternationalparam.php',
        'DHLClient\Model\GetInternationalParamsResponse' => __DIR__ .'/GetInternationalParamsResponse.php',
        'DHLClient\Model\getInternationalParamsResponse' => __DIR__ .'/getInternationalParamsResponse.php',
        'DHLClient\Model\getReturnParams' => __DIR__ .'/getReturnParams.php',
        'DHLClient\Model\ReturnParam' => __DIR__ .'/ReturnParam.php',
        'DHLClient\Model\ArrayOfReturnparam' => __DIR__ .'/ArrayOfReturnparam.php',
        'DHLClient\Model\GetReturnParamsResponse' => __DIR__ .'/GetReturnParamsResponse.php',
        'DHLClient\Model\getReturnParamsResponse' => __DIR__ .'/getReturnParamsResponse.php',
        'DHLClient\Model\ItemToLabelData' => __DIR__ .'/ItemToLabelData.php',
        'DHLClient\Model\ArrayOfItemtolabeldata' => __DIR__ .'/ArrayOfItemtolabeldata.php',
        'DHLClient\Model\getLabelsData' => __DIR__ .'/getLabelsData.php',
        'DHLClient\Model\ShipmentTimeLabelData' => __DIR__ .'/ShipmentTimeLabelData.php',
        'DHLClient\Model\Routing' => __DIR__ .'/Routing.php',
        'DHLClient\Model\ShipperAddressLabelData' => __DIR__ .'/ShipperAddressLabelData.php',
        'DHLClient\Model\ReceiverAddressLabelData' => __DIR__ .'/ReceiverAddressLabelData.php',
        'DHLClient\Model\ServicePoint' => __DIR__ .'/ServicePoint.php',
        'DHLClient\Model\LabelDataServiceDefinition' => __DIR__ .'/LabelDataServiceDefinition.php',
        'DHLClient\Model\PieceDefinitionLabelData' => __DIR__ .'/PieceDefinitionLabelData.php',
        'DHLClient\Model\ArrayOfPiecedefinitionlabeldata' => __DIR__ .'/ArrayOfPiecedefinitionlabeldata.php',
        'DHLClient\Model\ItemToLabelDataResponse' => __DIR__ .'/ItemToLabelDataResponse.php',
        'DHLClient\Model\ArrayOfItemtolabeldataresponse' => __DIR__ .'/ArrayOfItemtolabeldataresponse.php',
        'DHLClient\Model\getLabelsDataResponse' => __DIR__ .'/getLabelsDataResponse.php'
    );
    if (!empty($classes[$class])) {
        include $classes[$class];
    };
}

spl_autoload_register('autoload_982e3ab57777f1013a699229cb9c6f90');

// Do nothing. The rest is just leftovers from the code generation.
{
}
